[project]
name = "lorekeepers-ledger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "environs>=11.0.0",
    "scrapy>=2.11.2",
]

[tool.uv]
dev-dependencies = [
    "commitizen>=3.29.1",
    "ruff>=0.7.0",
]
